# Vælg .NET 6.0 runtime-billede til at bygge appen
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS build

# Opret en midlertidig mappe
WORKDIR /temp

# Kopier elforbrugapi.dll og runtime-konfigurationsfiler til den midlertidige mappe
COPY elforbrugapi.deps.json .
COPY elforbrugapi.dll .
COPY elforbrugapi.pdb .
COPY elforbrugapi.runtimeconfig.json .
COPY MySqlConnector.dll .
COPY Newtonsoft.Json.dll .

# Vælg .NET 6.0 runtime-billede til at køre din applikation
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS runtime

# Opret arbejdsmappe i runtime-containeren
WORKDIR /app

# Kopier DLL-filen og runtime-konfigurationsfilerne fra build-containeren til runtime-containeren
COPY --from=build /temp .

# Angiv kommando, der skal udføres, når containeren startes
CMD ["dotnet", "elforbrugapi.dll"]
